### ISSUE TITLE
getting error: 'module' object has no attribute MQTTClient

### ISSUE THREAD

**Issue by juanfgs** [gloveboxes/ESP32-MicroPython-BME280-MQTT-Sample#2]
I'm trying to run the umqtt client on an ESP32 (full name ESP-WROOM-32). I'm flashing the firmware with the firmware: http://micropython.org/resources/firmware/esp32-20171226-v1.9.3-217-g5de064fb.bin

And I'm getting the following error

~~~
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mqtt_start.py", line 6, in <module>
  File "/lib/umqtt/robust.py", line 4, in <module>
AttributeError: 'module' object has no attribute 'MQTTClient'
~~~

Could you please shed some light on what's going on here? I only removed the references to BME (since I'm not using that) but even running the original it doesn't work. It just fails with that error.

**Comment by ToftenAndi** [comment]
Same issue here....:(

**Comment by BoShek76** [comment]
Same error message here using a wemos lolin32.
